@startuml Langing Pages

!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist
!includeurl AWSPUML/common.puml
!includeurl AWSPUML/NetworkingContentDelivery/AmazonCloudFront/AmazonCloudFront.puml

AMAZONCLOUDFRONT(cloudfront)

[apps / de / es / fr / it / pl / pt / se / uk / www.babbel.com] --> Web
Web --> cloudfront

@enduml
